//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarRailDamage.Source.Core.LocalText.Marked.Text {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MarkedText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MarkedText() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StarRailDamage.Source.Core.LocalText.Marked.Text.MarkedText", typeof(MarkedText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 [{0}] 帖子点赞：{1} 的本地化字符串。
        /// </summary>
        public static string HoyolabForumPostUpvote {
            get {
                return ResourceManager.GetString("HoyolabForumPostUpvote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 社区签到：已签到 的本地化字符串。
        /// </summary>
        public static string HoyolabForumSign {
            get {
                return ResourceManager.GetString("HoyolabForumSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 社区签到
        ///
        ///&lt;社区ID&gt;
        ///社区的 GID
        ///1 - 崩坏3
        ///2 - 原神
        ///3 - 崩坏2
        ///4 - 未定事件簿
        ///5 - 大别墅
        ///6 - 崩坏：星穹铁道
        ///8 - 绝区零
        ///
        ///&lt;账号AID&gt; ( 可选 )
        ///米游社账号的 AID
        ///默认使用首个账号 的本地化字符串。
        /// </summary>
        public static string HoyolabForumSignCommandHelp {
            get {
                return ResourceManager.GetString("HoyolabForumSignCommandHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请前往米游社完成人机验证 的本地化字符串。
        /// </summary>
        public static string HoyolabForumSignWrong1034 {
            get {
                return ResourceManager.GetString("HoyolabForumSignWrong1034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开拓力 {0} / {1}
        ///回满 {2} 小时 {3} 分钟 的本地化字符串。
        /// </summary>
        public static string HoyolabGameNoteStamina {
            get {
                return ResourceManager.GetString("HoyolabGameNoteStamina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开拓力笔记
        ///
        ///&lt;账号AID&gt; ( 可选 )
        ///米游社账号的 AID
        ///默认使用首个账号 的本地化字符串。
        /// </summary>
        public static string HoyolabGameNoteStaminaCommandHelp {
            get {
                return ResourceManager.GetString("HoyolabGameNoteStaminaCommandHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 签到福利：已签到 的本地化字符串。
        /// </summary>
        public static string HoyolabGameSign {
            get {
                return ResourceManager.GetString("HoyolabGameSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 福利签到
        ///
        ///&lt;账号AID&gt; ( 可选 )
        ///米游社账号的 AID
        ///默认使用首个账号 的本地化字符串。
        /// </summary>
        public static string HoyolabGameSignCommandHelp {
            get {
                return ResourceManager.GetString("HoyolabGameSignCommandHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [{0}] {1} × {2} 的本地化字符串。
        /// </summary>
        public static string HoyolabGameSignReward {
            get {
                return ResourceManager.GetString("HoyolabGameSignReward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 签到奖励
        ///
        ///&lt;起始天&gt; ( 可选 )
        ///从指定的起始天数开始
        ///
        ///&lt;总天数&gt; ( 可选 )
        ///最多显示的行上限 的本地化字符串。
        /// </summary>
        public static string HoyolabGameSignRewardCommandHelp {
            get {
                return ResourceManager.GetString("HoyolabGameSignRewardCommandHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指定 AID 的账号不存在：&quot;{0}&quot; 的本地化字符串。
        /// </summary>
        public static string HoyolabNotFindToken {
            get {
                return ResourceManager.GetString("HoyolabNotFindToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏账号未注册：&quot;{0}&quot; 的本地化字符串。
        /// </summary>
        public static string HoyolabNotFindUserRole {
            get {
                return ResourceManager.GetString("HoyolabNotFindUserRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 浏览帖子
        ///
        ///&lt;帖子ID&gt;
        ///帖子对应的ID
        ///
        ///&lt;登录&gt; ( 可选 )
        ///登录账号以保留浏览记录
        ///[ True / False ( 默认值 ) ]
        ///
        ///&lt;账号AID&gt; ( 可选 )
        ///米游社账号的 AID
        ///默认使用首个账号 的本地化字符串。
        /// </summary>
        public static string HoyolabPostDetailCommandHelp {
            get {
                return ResourceManager.GetString("HoyolabPostDetailCommandHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最近帖子列表
        ///
        ///&lt;数量&gt;
        ///需要的帖子数量
        ///
        ///&lt;分区ID&gt;
        ///帖子所在分区的ID
        ///
        ///&lt;排序&gt; ( 可选 )
        ///帖子排序类别
        ///0 - 不指定 ( 默认值 )
        ///1 - 回复时间
        ///2 - 发布时间 的本地化字符串。
        /// </summary>
        public static string HoyolabPostNewsCommandHelp {
            get {
                return ResourceManager.GetString("HoyolabPostNewsCommandHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 帖子分享
        ///
        ///&lt;帖子ID&gt;
        ///帖子对应的ID
        ///
        ///&lt;账号AID&gt; ( 可选 )
        ///米游社账号的 AID
        ///默认使用首个账号 的本地化字符串。
        /// </summary>
        public static string HoyolabPostShareCommandHelp {
            get {
                return ResourceManager.GetString("HoyolabPostShareCommandHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 帖子点赞
        ///
        ///帖子ID&gt;
        ///帖子对应的ID
        ///
        ///&lt;取消点赞&gt; ( 可选 )
        ///是否取消对帖子的点赞
        ///[ True / False ( 默认值 ) ]
        ///
        ///&lt;账号AID&gt; ( 可选 )
        ///米游社账号的 AID
        ///默认使用首个账号 的本地化字符串。
        /// </summary>
        public static string HoyolabPostUpvoteCommandHelp {
            get {
                return ResourceManager.GetString("HoyolabPostUpvoteCommandHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 米游币任务
        ///
        ///&lt;账号AID&gt; ( 可选 )
        ///米游社账号的 AID，默认使用首个账号 的本地化字符串。
        /// </summary>
        public static string HoyolabUserMissionPerformCommandHelp {
            get {
                return ResourceManager.GetString("HoyolabUserMissionPerformCommandHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 米游币：{0}
        ///今日奖励：{1}
        ///打卡：{2} / 1
        ///浏览：{3} / 3
        ///点赞：{4} / 5
        ///分享：{5} / 1 的本地化字符串。
        /// </summary>
        public static string HoyolabUserMissionState {
            get {
                return ResourceManager.GetString("HoyolabUserMissionState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 米游币任务状态
        ///
        ///&lt;账号AID&gt; ( 可选 )
        ///米游社账号的 AID
        ///默认使用首个账号 的本地化字符串。
        /// </summary>
        public static string HoyolabUserMissionStateCommandHelp {
            get {
                return ResourceManager.GetString("HoyolabUserMissionStateCommandHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭控制台 的本地化字符串。
        /// </summary>
        public static string TerminalCommandCloseHelp {
            get {
                return ResourceManager.GetString("TerminalCommandCloseHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动控制台 的本地化字符串。
        /// </summary>
        public static string TerminalCommandEnableHelp {
            get {
                return ResourceManager.GetString("TerminalCommandEnableHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出控制台 的本地化字符串。
        /// </summary>
        public static string TerminalCommandExitedHelp {
            get {
                return ResourceManager.GetString("TerminalCommandExitedHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清空控制台 的本地化字符串。
        /// </summary>
        public static string TerminalCommandFlushHelp {
            get {
                return ResourceManager.GetString("TerminalCommandFlushHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 命令帮助
        ///
        ///&lt;命令名称&gt; ( 可选 )
        ///显示指定命令的参数信息 的本地化字符串。
        /// </summary>
        public static string TerminalCommandHelp {
            get {
                return ResourceManager.GetString("TerminalCommandHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 执行命令文本
        ///
        ///&lt;命令文本&gt;
        ///将要执行命令的文本 的本地化字符串。
        /// </summary>
        public static string TerminalCommandParseHelp {
            get {
                return ResourceManager.GetString("TerminalCommandParseHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按任意键继续...... 的本地化字符串。
        /// </summary>
        public static string TerminalCommandPause {
            get {
                return ResourceManager.GetString("TerminalCommandPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 等待输入 的本地化字符串。
        /// </summary>
        public static string TerminalCommandPauseHelp {
            get {
                return ResourceManager.GetString("TerminalCommandPauseHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打印控制台文本
        ///
        ///&lt;文本&gt;
        ///将要打印到控制台的文本 的本地化字符串。
        /// </summary>
        public static string TerminalCommandPrintHelp {
            get {
                return ResourceManager.GetString("TerminalCommandPrintHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 非法的参数
        ///使用 &quot;Help &lt;命令名称&gt;&quot; 查看帮助 的本地化字符串。
        /// </summary>
        public static string TerminalInvalidParameter {
            get {
                return ResourceManager.GetString("TerminalInvalidParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缺少必要参数
        ///使用 &quot;Help &lt;命令名称&gt;&quot; 查看帮助 的本地化字符串。
        /// </summary>
        public static string TerminalMissingParameter {
            get {
                return ResourceManager.GetString("TerminalMissingParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未知的命令：&quot;{0}&quot;
        ///使用 &quot;Help&quot; 查看帮助 的本地化字符串。
        /// </summary>
        public static string TerminalUnknownCommand {
            get {
                return ResourceManager.GetString("TerminalUnknownCommand", resourceCulture);
            }
        }
    }
}
