//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Source.Resource.Localization {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalString {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalString() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common.Source.Resource.Localization.LocalString", typeof(LocalString).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 运算符 &quot;{0}&quot; 可用的操作数不足 的本地化字符串。
        /// </summary>
        internal static string ServiceFormulaVerifyMissingOperand {
            get {
                return ResourceManager.GetString("ServiceFormulaVerifyMissingOperand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缀词符 &quot;{0}&quot; 不能像运算符一样使用 的本地化字符串。
        /// </summary>
        internal static string ServiceFormulaVerifyMisuseAffixeSymbol {
            get {
                return ResourceManager.GetString("ServiceFormulaVerifyMisuseAffixeSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运算符 &quot;{0}&quot; 左侧必须是可赋值对象 的本地化字符串。
        /// </summary>
        internal static string ServiceFormulaVerifyMisuseAssignSymbol {
            get {
                return ResourceManager.GetString("ServiceFormulaVerifyMisuseAssignSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {{0}}输入内容
        ///使用 &quot;{0}&quot; 来退出当前状态
        ///使用 &quot;{1}&quot; 来查看帮助 的本地化字符串。
        /// </summary>
        internal static string ServiceTerminalCycleHelp {
            get {
                return ResourceManager.GetString("ServiceTerminalCycleHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无可用的账号
        ///登录米游社账号后重试 的本地化字符串。
        /// </summary>
        internal static string ServiceTerminalHoyolabExceptionNotFindDefaultToken {
            get {
                return ResourceManager.GetString("ServiceTerminalHoyolabExceptionNotFindDefaultToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指定 AID 的账号不存在：&quot;{0}&quot; 的本地化字符串。
        /// </summary>
        internal static string ServiceTerminalHoyolabExceptionNotFindToken {
            get {
                return ResourceManager.GetString("ServiceTerminalHoyolabExceptionNotFindToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏账号未注册：&quot;{0}&quot; 的本地化字符串。
        /// </summary>
        internal static string ServiceTerminalHoyolabExceptionNotFindUserRole {
            get {
                return ResourceManager.GetString("ServiceTerminalHoyolabExceptionNotFindUserRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 浏览帖子 的本地化字符串。
        /// </summary>
        internal static string ServiceTerminalHoyolabForumDetailFullName {
            get {
                return ResourceManager.GetString("ServiceTerminalHoyolabForumDetailFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}帖子ID
        ///{1}是否登录 [True|False]
        ///{2}账号AID 的本地化字符串。
        /// </summary>
        internal static string ServiceTerminalHoyolabForumDetailHelp {
            get {
                return ResourceManager.GetString("ServiceTerminalHoyolabForumDetailHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最近帖子列表 的本地化字符串。
        /// </summary>
        internal static string ServiceTerminalHoyolabForumNewsFullName {
            get {
                return ResourceManager.GetString("ServiceTerminalHoyolabForumNewsFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}帖子数量
        ///{1}分区ID
        ///{2}排序方式 [0-不指定,1-回复时间,2-发布时间] 的本地化字符串。
        /// </summary>
        internal static string ServiceTerminalHoyolabForumNewsHelp {
            get {
                return ResourceManager.GetString("ServiceTerminalHoyolabForumNewsHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 帖子分享 的本地化字符串。
        /// </summary>
        internal static string ServiceTerminalHoyolabForumShareFullName {
            get {
                return ResourceManager.GetString("ServiceTerminalHoyolabForumShareFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}帖子ID
        ///{1}账号AID 的本地化字符串。
        /// </summary>
        internal static string ServiceTerminalHoyolabForumShareHelp {
            get {
                return ResourceManager.GetString("ServiceTerminalHoyolabForumShareHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 社区签到 的本地化字符串。
        /// </summary>
        internal static string ServiceTerminalHoyolabForumSignFullName {
            get {
                return ResourceManager.GetString("ServiceTerminalHoyolabForumSignFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}社区GID [1-崩坏3,2-原神,3-崩坏2,4-未定事件簿,5-大别墅,6-崩坏：星穹铁道,8-绝区零]
        ///{1}账号AID 的本地化字符串。
        /// </summary>
        internal static string ServiceTerminalHoyolabForumSignHelp {
            get {
                return ResourceManager.GetString("ServiceTerminalHoyolabForumSignHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 帖子点赞 的本地化字符串。
        /// </summary>
        internal static string ServiceTerminalHoyolabForumUpvoteFullName {
            get {
                return ResourceManager.GetString("ServiceTerminalHoyolabForumUpvoteFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}帖子ID
        ///{1}取消点赞 [True|False]
        ///{2}账号AID 的本地化字符串。
        /// </summary>
        internal static string ServiceTerminalHoyolabForumUpvoteHelp {
            get {
                return ResourceManager.GetString("ServiceTerminalHoyolabForumUpvoteHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 福利签到 的本地化字符串。
        /// </summary>
        internal static string ServiceTerminalHoyolabGameSignFullName {
            get {
                return ResourceManager.GetString("ServiceTerminalHoyolabGameSignFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}账号AID 的本地化字符串。
        /// </summary>
        internal static string ServiceTerminalHoyolabGameSignHelp {
            get {
                return ResourceManager.GetString("ServiceTerminalHoyolabGameSignHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 签到奖励 的本地化字符串。
        /// </summary>
        internal static string ServiceTerminalHoyolabGameSignRewardFullName {
            get {
                return ResourceManager.GetString("ServiceTerminalHoyolabGameSignRewardFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}起始天数
        ///{1}天数总和 的本地化字符串。
        /// </summary>
        internal static string ServiceTerminalHoyolabGameSignRewardHelp {
            get {
                return ResourceManager.GetString("ServiceTerminalHoyolabGameSignRewardHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开拓力笔记 的本地化字符串。
        /// </summary>
        internal static string ServiceTerminalHoyolabGameStaminaFullName {
            get {
                return ResourceManager.GetString("ServiceTerminalHoyolabGameStaminaFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}账号AID 的本地化字符串。
        /// </summary>
        internal static string ServiceTerminalHoyolabGameStaminaHelp {
            get {
                return ResourceManager.GetString("ServiceTerminalHoyolabGameStaminaHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备指纹 的本地化字符串。
        /// </summary>
        internal static string ServiceTerminalHoyolabLoginDeviceFpFullName {
            get {
                return ResourceManager.GetString("ServiceTerminalHoyolabLoginDeviceFpFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建登录请求 的本地化字符串。
        /// </summary>
        internal static string ServiceTerminalHoyolabLoginQRLoginCreate {
            get {
                return ResourceManager.GetString("ServiceTerminalHoyolabLoginQRLoginCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录已取消或超时 的本地化字符串。
        /// </summary>
        internal static string ServiceTerminalHoyolabLoginQRLoginExceptionCanceled {
            get {
                return ResourceManager.GetString("ServiceTerminalHoyolabLoginQRLoginExceptionCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 二维码登录 的本地化字符串。
        /// </summary>
        internal static string ServiceTerminalHoyolabLoginQRLoginFullName {
            get {
                return ResourceManager.GetString("ServiceTerminalHoyolabLoginQRLoginFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在设置令牌 {0} 的本地化字符串。
        /// </summary>
        internal static string ServiceTerminalHoyolabLoginQRLoginGetToken {
            get {
                return ResourceManager.GetString("ServiceTerminalHoyolabLoginQRLoginGetToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}设备标识符 的本地化字符串。
        /// </summary>
        internal static string ServiceTerminalHoyolabLoginQRLoginHelp {
            get {
                return ResourceManager.GetString("ServiceTerminalHoyolabLoginQRLoginHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 等待扫描确认 的本地化字符串。
        /// </summary>
        internal static string ServiceTerminalHoyolabLoginQRLoginShowQRCode {
            get {
                return ResourceManager.GetString("ServiceTerminalHoyolabLoginQRLoginShowQRCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 令牌登录 的本地化字符串。
        /// </summary>
        internal static string ServiceTerminalHoyolabLoginUserLoginFullName {
            get {
                return ResourceManager.GetString("ServiceTerminalHoyolabLoginUserLoginFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发起设备指纹请求 的本地化字符串。
        /// </summary>
        internal static string ServiceTerminalHoyolabLoginUserLoginGetDeviceFp {
            get {
                return ResourceManager.GetString("ServiceTerminalHoyolabLoginUserLoginGetDeviceFp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在交换令牌 {0} 的本地化字符串。
        /// </summary>
        internal static string ServiceTerminalHoyolabLoginUserLoginGetToken {
            get {
                return ResourceManager.GetString("ServiceTerminalHoyolabLoginUserLoginGetToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拉取游戏角色列表 的本地化字符串。
        /// </summary>
        internal static string ServiceTerminalHoyolabLoginUserLoginGetUserRole {
            get {
                return ResourceManager.GetString("ServiceTerminalHoyolabLoginUserLoginGetUserRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}账号MID
        ///{1}账号SToken
        ///{2}设备标识符 的本地化字符串。
        /// </summary>
        internal static string ServiceTerminalHoyolabLoginUserLoginHelp {
            get {
                return ResourceManager.GetString("ServiceTerminalHoyolabLoginUserLoginHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 账号数据已更新 的本地化字符串。
        /// </summary>
        internal static string ServiceTerminalHoyolabLoginUserLoginSuccess {
            get {
                return ResourceManager.GetString("ServiceTerminalHoyolabLoginUserLoginSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在更新本地数据 的本地化字符串。
        /// </summary>
        internal static string ServiceTerminalHoyolabLoginUserLoginTryUpdate {
            get {
                return ResourceManager.GetString("ServiceTerminalHoyolabLoginUserLoginTryUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 米游币任务 的本地化字符串。
        /// </summary>
        internal static string ServiceTerminalHoyolabUserMissionFullName {
            get {
                return ResourceManager.GetString("ServiceTerminalHoyolabUserMissionFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}账号AID 的本地化字符串。
        /// </summary>
        internal static string ServiceTerminalHoyolabUserMissionHelp {
            get {
                return ResourceManager.GetString("ServiceTerminalHoyolabUserMissionHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询米游币任务 的本地化字符串。
        /// </summary>
        internal static string ServiceTerminalHoyolabUserMissionInfoFullName {
            get {
                return ResourceManager.GetString("ServiceTerminalHoyolabUserMissionInfoFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}账号AID 的本地化字符串。
        /// </summary>
        internal static string ServiceTerminalHoyolabUserMissionInfoHelp {
            get {
                return ResourceManager.GetString("ServiceTerminalHoyolabUserMissionInfoHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清空控制台 的本地化字符串。
        /// </summary>
        internal static string ServiceTerminalSupportConsoleClearFullName {
            get {
                return ResourceManager.GetString("ServiceTerminalSupportConsoleClearFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输出到控制台 的本地化字符串。
        /// </summary>
        internal static string ServiceTerminalSupportConsoleEchoFullName {
            get {
                return ResourceManager.GetString("ServiceTerminalSupportConsoleEchoFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}输出文本 的本地化字符串。
        /// </summary>
        internal static string ServiceTerminalSupportConsoleEchoHelp {
            get {
                return ResourceManager.GetString("ServiceTerminalSupportConsoleEchoHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出控制台 的本地化字符串。
        /// </summary>
        internal static string ServiceTerminalSupportConsoleExitFullName {
            get {
                return ResourceManager.GetString("ServiceTerminalSupportConsoleExitFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 命令帮助 的本地化字符串。
        /// </summary>
        internal static string ServiceTerminalSupportConsoleHelpFullName {
            get {
                return ResourceManager.GetString("ServiceTerminalSupportConsoleHelpFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}命令名称
        ///命令的使用语法
        ///使用 &quot;&amp;&quot; 来分隔命令
        ///使用 &quot;-&quot; 来指定选项
        ///使用 &quot;--&quot; 来启用开关
        ///使用 &quot;&quot;&quot; 来拼接内容
        ///使用 &quot;\&quot; 来转义符号 的本地化字符串。
        /// </summary>
        internal static string ServiceTerminalSupportConsoleHelpHelp {
            get {
                return ResourceManager.GetString("ServiceTerminalSupportConsoleHelpHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 执行命令 的本地化字符串。
        /// </summary>
        internal static string ServiceTerminalSupportConsoleInvokeFullName {
            get {
                return ResourceManager.GetString("ServiceTerminalSupportConsoleInvokeFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}命令内容 的本地化字符串。
        /// </summary>
        internal static string ServiceTerminalSupportConsoleInvokeHelp {
            get {
                return ResourceManager.GetString("ServiceTerminalSupportConsoleInvokeHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按任意键继续...... 的本地化字符串。
        /// </summary>
        internal static string ServiceTerminalSupportConsolePauseContent {
            get {
                return ResourceManager.GetString("ServiceTerminalSupportConsolePauseContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 等待输入 的本地化字符串。
        /// </summary>
        internal static string ServiceTerminalSupportConsolePauseFullName {
            get {
                return ResourceManager.GetString("ServiceTerminalSupportConsolePauseFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缺少必要参数
        ///使用 &quot;Help &lt;命令名称&gt;&quot; 查看帮助 的本地化字符串。
        /// </summary>
        internal static string ServiceTerminalSupportExceptionMissingParameter {
            get {
                return ResourceManager.GetString("ServiceTerminalSupportExceptionMissingParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未知的命令：&quot;{0}&quot;
        ///使用 &quot;Help&quot; 查看帮助 的本地化字符串。
        /// </summary>
        internal static string ServiceTerminalSupportExceptionUnknownOperation {
            get {
                return ResourceManager.GetString("ServiceTerminalSupportExceptionUnknownOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 非法的参数
        ///使用 &quot;Help &lt;命令名称&gt;&quot; 查看帮助 的本地化字符串。
        /// </summary>
        internal static string ServiceTerminalSupportExceptionUnlawfulParameter {
            get {
                return ResourceManager.GetString("ServiceTerminalSupportExceptionUnlawfulParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 算式运算器 的本地化字符串。
        /// </summary>
        internal static string ServiceTerminalSupportFormulaCycleFullName {
            get {
                return ResourceManager.GetString("ServiceTerminalSupportFormulaCycleFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运算符优先级
        ///[1] 赋值运算符 [=,+=,-=,*=,/=]
        ///[2] 逻辑或运算符 [|,||]
        ///[3] 逻辑与运算符 [&amp;,&amp;&amp;]
        ///[4] 比较运算符 [&gt;,&gt;=,&lt;,&lt;=,==,!=]
        ///[5] 加减运算符 [+,-]
        ///[6] 乘除运算符 [*,/]
        ///[7] 幂运算符 [^]
        ///[8] 逻辑非符号 [!]
        ///[8] 百分比符号 [%]
        ///[9] 函数方法 [func(n,m)] 的本地化字符串。
        /// </summary>
        internal static string ServiceTerminalSupportFormulaCycleHelp {
            get {
                return ResourceManager.GetString("ServiceTerminalSupportFormulaCycleHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模式-{0}, 版本-{1}, 纠错-{2}, 掩码-{3} 的本地化字符串。
        /// </summary>
        internal static string ServiceTerminalSupportQRCodeMakerDetails {
            get {
                return ResourceManager.GetString("ServiceTerminalSupportQRCodeMakerDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 二维码生成 的本地化字符串。
        /// </summary>
        internal static string ServiceTerminalSupportQRCodeMakerFullName {
            get {
                return ResourceManager.GetString("ServiceTerminalSupportQRCodeMakerFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}内容文本
        ///{1}保存路径
        ///{2}文件格式 [Png|Jpg|Bmp|Svg|Csv]
        ///{3}前景色 (#000000)
        ///{4}背景色 (#FFFFFF)
        ///{5}单格像素 (5)
        ///{6}填充边距 (20)
        ///{7}版本 [1-40]
        ///{8}编码器 [1-数字,2-字母,3-字节]
        ///{9}纠错级别 (M) [L-低,M-中,Q-高,H-最高]
        ///{10}掩码图案 [1-8]
        ///{11}是否跳转 [True|False] 的本地化字符串。
        /// </summary>
        internal static string ServiceTerminalSupportQRCodeMakerHelp {
            get {
                return ResourceManager.GetString("ServiceTerminalSupportQRCodeMakerHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不支持的文件格式 的本地化字符串。
        /// </summary>
        internal static string ServiceTerminalSupportQRCodeMakerUnSupportedFormat {
            get {
                return ResourceManager.GetString("ServiceTerminalSupportQRCodeMakerUnSupportedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请前往米游社完成人机验证 的本地化字符串。
        /// </summary>
        internal static string WebHoyolabForumSignFailed1034 {
            get {
                return ResourceManager.GetString("WebHoyolabForumSignFailed1034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 社区签到：已签到 的本地化字符串。
        /// </summary>
        internal static string WebHoyolabForumSignSuccess {
            get {
                return ResourceManager.GetString("WebHoyolabForumSignSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [{0}] 取消点赞 的本地化字符串。
        /// </summary>
        internal static string WebHoyolabForumUpvoteCancelSuccess {
            get {
                return ResourceManager.GetString("WebHoyolabForumUpvoteCancelSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [{0}] 已点赞 的本地化字符串。
        /// </summary>
        internal static string WebHoyolabForumUpvoteSuccess {
            get {
                return ResourceManager.GetString("WebHoyolabForumUpvoteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [{0}] {1} × {2} 的本地化字符串。
        /// </summary>
        internal static string WebHoyolabGameSignRewardItem {
            get {
                return ResourceManager.GetString("WebHoyolabGameSignRewardItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 签到福利：已签到 的本地化字符串。
        /// </summary>
        internal static string WebHoyolabGameSignSuccess {
            get {
                return ResourceManager.GetString("WebHoyolabGameSignSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开拓力 {0} / {1}
        ///回满 {2} 小时 {3} 分钟 的本地化字符串。
        /// </summary>
        internal static string WebHoyolabGameStaminaContent {
            get {
                return ResourceManager.GetString("WebHoyolabGameStaminaContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 米游币：{0}
        ///今日奖励：{1}
        ///打卡：{2} / 1
        ///浏览：{3} / 3
        ///点赞：{4} / 5
        ///分享：{5} / 1 的本地化字符串。
        /// </summary>
        internal static string WebHoyolabUserMissionInfoContent {
            get {
                return ResourceManager.GetString("WebHoyolabUserMissionInfoContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 网络请求已取消 的本地化字符串。
        /// </summary>
        internal static string WebRequestExceptionOperationCanceled {
            get {
                return ResourceManager.GetString("WebRequestExceptionOperationCanceled", resourceCulture);
            }
        }
    }
}
