//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UIDesign.Source.Resource.Localization {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalString {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalString() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StarRail.Source.Resource.Localization.LocalString", typeof(LocalString).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 攻击力 的本地化字符串。
        /// </summary>
        internal static string CharacterAttributeAttack {
            get {
                return ResourceManager.GetString("CharacterAttributeAttack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 基础攻击 的本地化字符串。
        /// </summary>
        internal static string CharacterAttributeAttackBase {
            get {
                return ResourceManager.GetString("CharacterAttributeAttackBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 击破特攻 的本地化字符串。
        /// </summary>
        internal static string CharacterAttributeBreakEffect {
            get {
                return ResourceManager.GetString("CharacterAttributeBreakEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 击破效率 的本地化字符串。
        /// </summary>
        internal static string CharacterAttributeBreakEfficiency {
            get {
                return ResourceManager.GetString("CharacterAttributeBreakEfficiency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 击破增伤 的本地化字符串。
        /// </summary>
        internal static string CharacterAttributeBreakIncrease {
            get {
                return ResourceManager.GetString("CharacterAttributeBreakIncrease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 暴击伤害 的本地化字符串。
        /// </summary>
        internal static string CharacterAttributeCriticalHitDamage {
            get {
                return ResourceManager.GetString("CharacterAttributeCriticalHitDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 暴击率 的本地化字符串。
        /// </summary>
        internal static string CharacterAttributeCriticalHitRate {
            get {
                return ResourceManager.GetString("CharacterAttributeCriticalHitRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 免伤 的本地化字符串。
        /// </summary>
        internal static string CharacterAttributeDamageDecrease {
            get {
                return ResourceManager.GetString("CharacterAttributeDamageDecrease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 易伤 的本地化字符串。
        /// </summary>
        internal static string CharacterAttributeDamageIncrease {
            get {
                return ResourceManager.GetString("CharacterAttributeDamageIncrease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 防御力 的本地化字符串。
        /// </summary>
        internal static string CharacterAttributeDefense {
            get {
                return ResourceManager.GetString("CharacterAttributeDefense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 基础防御 的本地化字符串。
        /// </summary>
        internal static string CharacterAttributeDefenseBase {
            get {
                return ResourceManager.GetString("CharacterAttributeDefenseBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无视防御 的本地化字符串。
        /// </summary>
        internal static string CharacterAttributeDefenseDecrease {
            get {
                return ResourceManager.GetString("CharacterAttributeDefenseDecrease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 效果命中 的本地化字符串。
        /// </summary>
        internal static string CharacterAttributeEffectHitRate {
            get {
                return ResourceManager.GetString("CharacterAttributeEffectHitRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 效果抵抗 的本地化字符串。
        /// </summary>
        internal static string CharacterAttributeEffectMagical {
            get {
                return ResourceManager.GetString("CharacterAttributeEffectMagical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 好活当赏 的本地化字符串。
        /// </summary>
        internal static string CharacterAttributeElationBonus {
            get {
                return ResourceManager.GetString("CharacterAttributeElationBonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 欢愉度 的本地化字符串。
        /// </summary>
        internal static string CharacterAttributeElationIncrease {
            get {
                return ResourceManager.GetString("CharacterAttributeElationIncrease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 伤害提高 的本地化字符串。
        /// </summary>
        internal static string CharacterAttributeElementIncrease {
            get {
                return ResourceManager.GetString("CharacterAttributeElementIncrease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 治疗提高 的本地化字符串。
        /// </summary>
        internal static string CharacterAttributeHealingBoost {
            get {
                return ResourceManager.GetString("CharacterAttributeHealingBoost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生命值 的本地化字符串。
        /// </summary>
        internal static string CharacterAttributeHealth {
            get {
                return ResourceManager.GetString("CharacterAttributeHealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 基础生命 的本地化字符串。
        /// </summary>
        internal static string CharacterAttributeHealthBase {
            get {
                return ResourceManager.GetString("CharacterAttributeHealthBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 抗性穿透 的本地化字符串。
        /// </summary>
        internal static string CharacterAttributeMagicalDecrease {
            get {
                return ResourceManager.GetString("CharacterAttributeMagicalDecrease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 抗性 的本地化字符串。
        /// </summary>
        internal static string CharacterAttributeMagicalIncrease {
            get {
                return ResourceManager.GetString("CharacterAttributeMagicalIncrease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 充能效率 的本地化字符串。
        /// </summary>
        internal static string CharacterAttributeManaReplenish {
            get {
                return ResourceManager.GetString("CharacterAttributeManaReplenish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 能量上限 的本地化字符串。
        /// </summary>
        internal static string CharacterAttributeMaximumEnergy {
            get {
                return ResourceManager.GetString("CharacterAttributeMaximumEnergy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 怪物数量 的本地化字符串。
        /// </summary>
        internal static string CharacterAttributeMonsterCount {
            get {
                return ResourceManager.GetString("CharacterAttributeMonsterCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 怪物等级 的本地化字符串。
        /// </summary>
        internal static string CharacterAttributeMonsterLevel {
            get {
                return ResourceManager.GetString("CharacterAttributeMonsterLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 速度 的本地化字符串。
        /// </summary>
        internal static string CharacterAttributeSpeed {
            get {
                return ResourceManager.GetString("CharacterAttributeSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 基础速度 的本地化字符串。
        /// </summary>
        internal static string CharacterAttributeSpeedBase {
            get {
                return ResourceManager.GetString("CharacterAttributeSpeedBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 削韧值 的本地化字符串。
        /// </summary>
        internal static string CharacterAttributeToughDecline {
            get {
                return ResourceManager.GetString("CharacterAttributeToughDecline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 韧性值 的本地化字符串。
        /// </summary>
        internal static string CharacterAttributeToughness {
            get {
                return ResourceManager.GetString("CharacterAttributeToughness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色等级 的本地化字符串。
        /// </summary>
        internal static string CharacterAttributeWonsterLevel {
            get {
                return ResourceManager.GetString("CharacterAttributeWonsterLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 灼烧 的本地化字符串。
        /// </summary>
        internal static string CharacterDelayedDamageFire {
            get {
                return ResourceManager.GetString("CharacterDelayedDamageFire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 冻结 的本地化字符串。
        /// </summary>
        internal static string CharacterDelayedDamageIce {
            get {
                return ResourceManager.GetString("CharacterDelayedDamageIce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 禁锢 的本地化字符串。
        /// </summary>
        internal static string CharacterDelayedDamageImaginary {
            get {
                return ResourceManager.GetString("CharacterDelayedDamageImaginary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 触电 的本地化字符串。
        /// </summary>
        internal static string CharacterDelayedDamageLightning {
            get {
                return ResourceManager.GetString("CharacterDelayedDamageLightning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 裂伤 的本地化字符串。
        /// </summary>
        internal static string CharacterDelayedDamagePhysical {
            get {
                return ResourceManager.GetString("CharacterDelayedDamagePhysical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 纠缠 的本地化字符串。
        /// </summary>
        internal static string CharacterDelayedDamageQuantum {
            get {
                return ResourceManager.GetString("CharacterDelayedDamageQuantum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 风化 的本地化字符串。
        /// </summary>
        internal static string CharacterDelayedDamageWind {
            get {
                return ResourceManager.GetString("CharacterDelayedDamageWind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 火 的本地化字符串。
        /// </summary>
        internal static string CharacterElementFire {
            get {
                return ResourceManager.GetString("CharacterElementFire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 冰 的本地化字符串。
        /// </summary>
        internal static string CharacterElementIce {
            get {
                return ResourceManager.GetString("CharacterElementIce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 虚数 的本地化字符串。
        /// </summary>
        internal static string CharacterElementImaginary {
            get {
                return ResourceManager.GetString("CharacterElementImaginary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 雷 的本地化字符串。
        /// </summary>
        internal static string CharacterElementLightning {
            get {
                return ResourceManager.GetString("CharacterElementLightning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物理 的本地化字符串。
        /// </summary>
        internal static string CharacterElementPhysical {
            get {
                return ResourceManager.GetString("CharacterElementPhysical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 量子 的本地化字符串。
        /// </summary>
        internal static string CharacterElementQuantum {
            get {
                return ResourceManager.GetString("CharacterElementQuantum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 风 的本地化字符串。
        /// </summary>
        internal static string CharacterElementWind {
            get {
                return ResourceManager.GetString("CharacterElementWind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 击破伤害 的本地化字符串。
        /// </summary>
        internal static string CharacterFinalizeDamageBreak {
            get {
                return ResourceManager.GetString("CharacterFinalizeDamageBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全暴击伤害 的本地化字符串。
        /// </summary>
        internal static string CharacterFinalizeDamageCritical {
            get {
                return ResourceManager.GetString("CharacterFinalizeDamageCritical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 持续伤害 的本地化字符串。
        /// </summary>
        internal static string CharacterFinalizeDamageDelay {
            get {
                return ResourceManager.GetString("CharacterFinalizeDamageDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 欢愉伤害 的本地化字符串。
        /// </summary>
        internal static string CharacterFinalizeDamageElation {
            get {
                return ResourceManager.GetString("CharacterFinalizeDamageElation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 基础伤害 的本地化字符串。
        /// </summary>
        internal static string CharacterFinalizeDamageNormal {
            get {
                return ResourceManager.GetString("CharacterFinalizeDamageNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 超击破伤害 的本地化字符串。
        /// </summary>
        internal static string CharacterFinalizeDamageSuperBreak {
            get {
                return ResourceManager.GetString("CharacterFinalizeDamageSuperBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 丰饶 的本地化字符串。
        /// </summary>
        internal static string CharacterOccupationAbundance {
            get {
                return ResourceManager.GetString("CharacterOccupationAbundance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 毁灭 的本地化字符串。
        /// </summary>
        internal static string CharacterOccupationDestruction {
            get {
                return ResourceManager.GetString("CharacterOccupationDestruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 欢愉 的本地化字符串。
        /// </summary>
        internal static string CharacterOccupationElation {
            get {
                return ResourceManager.GetString("CharacterOccupationElation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 智识 的本地化字符串。
        /// </summary>
        internal static string CharacterOccupationErudition {
            get {
                return ResourceManager.GetString("CharacterOccupationErudition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 同协 的本地化字符串。
        /// </summary>
        internal static string CharacterOccupationHarmony {
            get {
                return ResourceManager.GetString("CharacterOccupationHarmony", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 记忆 的本地化字符串。
        /// </summary>
        internal static string CharacterOccupationMemory {
            get {
                return ResourceManager.GetString("CharacterOccupationMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 命途 的本地化字符串。
        /// </summary>
        internal static string CharacterOccupationName {
            get {
                return ResourceManager.GetString("CharacterOccupationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 虚无 的本地化字符串。
        /// </summary>
        internal static string CharacterOccupationNihility {
            get {
                return ResourceManager.GetString("CharacterOccupationNihility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 存护 的本地化字符串。
        /// </summary>
        internal static string CharacterOccupationPreservation {
            get {
                return ResourceManager.GetString("CharacterOccupationPreservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 巡猎 的本地化字符串。
        /// </summary>
        internal static string CharacterOccupationTheHunt {
            get {
                return ResourceManager.GetString("CharacterOccupationTheHunt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 算式 的本地化字符串。
        /// </summary>
        internal static string ViewControlFormulaSpanTitle {
            get {
                return ResourceManager.GetString("ViewControlFormulaSpanTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        internal static string ViewDialogConfirmActionAccept {
            get {
                return ResourceManager.GetString("ViewDialogConfirmActionAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        internal static string ViewDialogConfirmActionCancel {
            get {
                return ResourceManager.GetString("ViewDialogConfirmActionCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 切换 的本地化字符串。
        /// </summary>
        internal static string ViewPageMockBattleActionChange {
            get {
                return ResourceManager.GetString("ViewPageMockBattleActionChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出 的本地化字符串。
        /// </summary>
        internal static string ViewPageMockBattleActionExport {
            get {
                return ResourceManager.GetString("ViewPageMockBattleActionExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 的本地化字符串。
        /// </summary>
        internal static string ViewPageMockBattleActionSave {
            get {
                return ResourceManager.GetString("ViewPageMockBattleActionSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置 的本地化字符串。
        /// </summary>
        internal static string ViewPageMockBattleActionSetting {
            get {
                return ResourceManager.GetString("ViewPageMockBattleActionSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 级 的本地化字符串。
        /// </summary>
        internal static string ViewPageMockBattleUnitLevel {
            get {
                return ResourceManager.GetString("ViewPageMockBattleUnitLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 % 的本地化字符串。
        /// </summary>
        internal static string ViewPageMockBattleUnitModulo {
            get {
                return ResourceManager.GetString("ViewPageMockBattleUnitModulo", resourceCulture);
            }
        }
    }
}
