//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarRailDamage.Source.Resource.Localization {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FixedText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FixedText() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StarRailDamage.Source.Resource.Localization.FixedText", typeof(FixedText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 攻击力 的本地化字符串。
        /// </summary>
        public static string AttributeAttack {
            get {
                return ResourceManager.GetString("AttributeAttack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 基础攻击 的本地化字符串。
        /// </summary>
        public static string AttributeAttackBase {
            get {
                return ResourceManager.GetString("AttributeAttackBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 击破特攻 的本地化字符串。
        /// </summary>
        public static string AttributeBreakEffect {
            get {
                return ResourceManager.GetString("AttributeBreakEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 击破效率 的本地化字符串。
        /// </summary>
        public static string AttributeBreakEfficiency {
            get {
                return ResourceManager.GetString("AttributeBreakEfficiency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 击破增伤 的本地化字符串。
        /// </summary>
        public static string AttributeBreakIncrease {
            get {
                return ResourceManager.GetString("AttributeBreakIncrease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 暴击伤害 的本地化字符串。
        /// </summary>
        public static string AttributeCriticalHitDamage {
            get {
                return ResourceManager.GetString("AttributeCriticalHitDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 暴击率 的本地化字符串。
        /// </summary>
        public static string AttributeCriticalHitRate {
            get {
                return ResourceManager.GetString("AttributeCriticalHitRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 免伤 的本地化字符串。
        /// </summary>
        public static string AttributeDamageDecrease {
            get {
                return ResourceManager.GetString("AttributeDamageDecrease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 易伤 的本地化字符串。
        /// </summary>
        public static string AttributeDamageIncrease {
            get {
                return ResourceManager.GetString("AttributeDamageIncrease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 防御力 的本地化字符串。
        /// </summary>
        public static string AttributeDefense {
            get {
                return ResourceManager.GetString("AttributeDefense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 基础防御 的本地化字符串。
        /// </summary>
        public static string AttributeDefenseBase {
            get {
                return ResourceManager.GetString("AttributeDefenseBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无视防御 的本地化字符串。
        /// </summary>
        public static string AttributeDefenseDecrease {
            get {
                return ResourceManager.GetString("AttributeDefenseDecrease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 效果命中 的本地化字符串。
        /// </summary>
        public static string AttributeEffectHitRate {
            get {
                return ResourceManager.GetString("AttributeEffectHitRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 效果抵抗 的本地化字符串。
        /// </summary>
        public static string AttributeEffectMagical {
            get {
                return ResourceManager.GetString("AttributeEffectMagical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 好活当赏 的本地化字符串。
        /// </summary>
        public static string AttributeElationBonus {
            get {
                return ResourceManager.GetString("AttributeElationBonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 伤害提高 的本地化字符串。
        /// </summary>
        public static string AttributeElementIncrease {
            get {
                return ResourceManager.GetString("AttributeElementIncrease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 治疗提高 的本地化字符串。
        /// </summary>
        public static string AttributeHealingBoost {
            get {
                return ResourceManager.GetString("AttributeHealingBoost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生命值 的本地化字符串。
        /// </summary>
        public static string AttributeHealth {
            get {
                return ResourceManager.GetString("AttributeHealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 基础生命 的本地化字符串。
        /// </summary>
        public static string AttributeHealthBase {
            get {
                return ResourceManager.GetString("AttributeHealthBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 抗性穿透 的本地化字符串。
        /// </summary>
        public static string AttributeMagicalDecrease {
            get {
                return ResourceManager.GetString("AttributeMagicalDecrease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 抗性 的本地化字符串。
        /// </summary>
        public static string AttributeMagicalIncrease {
            get {
                return ResourceManager.GetString("AttributeMagicalIncrease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 充能效率 的本地化字符串。
        /// </summary>
        public static string AttributeManaReplenish {
            get {
                return ResourceManager.GetString("AttributeManaReplenish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 能量上限 的本地化字符串。
        /// </summary>
        public static string AttributeMaximumEnergy {
            get {
                return ResourceManager.GetString("AttributeMaximumEnergy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 怪物数量 的本地化字符串。
        /// </summary>
        public static string AttributeMonsterCount {
            get {
                return ResourceManager.GetString("AttributeMonsterCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 怪物等级 的本地化字符串。
        /// </summary>
        public static string AttributeMonsterLevel {
            get {
                return ResourceManager.GetString("AttributeMonsterLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 速度 的本地化字符串。
        /// </summary>
        public static string AttributeSpeed {
            get {
                return ResourceManager.GetString("AttributeSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 基础速度 的本地化字符串。
        /// </summary>
        public static string AttributeSpeedBase {
            get {
                return ResourceManager.GetString("AttributeSpeedBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 超击破 的本地化字符串。
        /// </summary>
        public static string AttributeSuperBreakEqual {
            get {
                return ResourceManager.GetString("AttributeSuperBreakEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 削韧值 的本地化字符串。
        /// </summary>
        public static string AttributeToughDecline {
            get {
                return ResourceManager.GetString("AttributeToughDecline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 韧性值 的本地化字符串。
        /// </summary>
        public static string AttributeToughness {
            get {
                return ResourceManager.GetString("AttributeToughness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色等级 的本地化字符串。
        /// </summary>
        public static string AttributeWonsterLevel {
            get {
                return ResourceManager.GetString("AttributeWonsterLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        public static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 切换 的本地化字符串。
        /// </summary>
        public static string ButtonChange {
            get {
                return ResourceManager.GetString("ButtonChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认 的本地化字符串。
        /// </summary>
        public static string ButtonConfirm {
            get {
                return ResourceManager.GetString("ButtonConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出 的本地化字符串。
        /// </summary>
        public static string ButtonExport {
            get {
                return ResourceManager.GetString("ButtonExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 的本地化字符串。
        /// </summary>
        public static string ButtonSave {
            get {
                return ResourceManager.GetString("ButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置 的本地化字符串。
        /// </summary>
        public static string ButtonSetting {
            get {
                return ResourceManager.GetString("ButtonSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 击破伤害 的本地化字符串。
        /// </summary>
        public static string DamageBreak {
            get {
                return ResourceManager.GetString("DamageBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全暴击伤害 的本地化字符串。
        /// </summary>
        public static string DamageCritical {
            get {
                return ResourceManager.GetString("DamageCritical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 持续伤害 的本地化字符串。
        /// </summary>
        public static string DamageDelay {
            get {
                return ResourceManager.GetString("DamageDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 欢愉伤害 的本地化字符串。
        /// </summary>
        public static string DamageElation {
            get {
                return ResourceManager.GetString("DamageElation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 基础伤害 的本地化字符串。
        /// </summary>
        public static string DamageNormal {
            get {
                return ResourceManager.GetString("DamageNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 超击破伤害 的本地化字符串。
        /// </summary>
        public static string DamageSuperBreak {
            get {
                return ResourceManager.GetString("DamageSuperBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 灼烧 的本地化字符串。
        /// </summary>
        public static string DelayedFire {
            get {
                return ResourceManager.GetString("DelayedFire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 冻结 的本地化字符串。
        /// </summary>
        public static string DelayedIce {
            get {
                return ResourceManager.GetString("DelayedIce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 禁锢 的本地化字符串。
        /// </summary>
        public static string DelayedImaginary {
            get {
                return ResourceManager.GetString("DelayedImaginary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 触电 的本地化字符串。
        /// </summary>
        public static string DelayedLightning {
            get {
                return ResourceManager.GetString("DelayedLightning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 裂伤 的本地化字符串。
        /// </summary>
        public static string DelayedPhysical {
            get {
                return ResourceManager.GetString("DelayedPhysical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 纠缠 的本地化字符串。
        /// </summary>
        public static string DelayedQuantum {
            get {
                return ResourceManager.GetString("DelayedQuantum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 风化 的本地化字符串。
        /// </summary>
        public static string DelayedWind {
            get {
                return ResourceManager.GetString("DelayedWind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色属性 的本地化字符串。
        /// </summary>
        public static string ElementCharacter {
            get {
                return ResourceManager.GetString("ElementCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 火 的本地化字符串。
        /// </summary>
        public static string ElementFire {
            get {
                return ResourceManager.GetString("ElementFire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 冰 的本地化字符串。
        /// </summary>
        public static string ElementIce {
            get {
                return ResourceManager.GetString("ElementIce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 虚数 的本地化字符串。
        /// </summary>
        public static string ElementImaginary {
            get {
                return ResourceManager.GetString("ElementImaginary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 雷 的本地化字符串。
        /// </summary>
        public static string ElementLightning {
            get {
                return ResourceManager.GetString("ElementLightning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物理 的本地化字符串。
        /// </summary>
        public static string ElementPhysical {
            get {
                return ResourceManager.GetString("ElementPhysical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 量子 的本地化字符串。
        /// </summary>
        public static string ElementQuantum {
            get {
                return ResourceManager.GetString("ElementQuantum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 风 的本地化字符串。
        /// </summary>
        public static string ElementWind {
            get {
                return ResourceManager.GetString("ElementWind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 简体中文 的本地化字符串。
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 算式 的本地化字符串。
        /// </summary>
        public static string NumberTextBoxTitle {
            get {
                return ResourceManager.GetString("NumberTextBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 丰饶 的本地化字符串。
        /// </summary>
        public static string OccupationAbundance {
            get {
                return ResourceManager.GetString("OccupationAbundance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 毁灭 的本地化字符串。
        /// </summary>
        public static string OccupationDestruction {
            get {
                return ResourceManager.GetString("OccupationDestruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 欢愉 的本地化字符串。
        /// </summary>
        public static string OccupationElation {
            get {
                return ResourceManager.GetString("OccupationElation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 智识 的本地化字符串。
        /// </summary>
        public static string OccupationErudition {
            get {
                return ResourceManager.GetString("OccupationErudition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 同协 的本地化字符串。
        /// </summary>
        public static string OccupationHarmony {
            get {
                return ResourceManager.GetString("OccupationHarmony", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 记忆 的本地化字符串。
        /// </summary>
        public static string OccupationMemory {
            get {
                return ResourceManager.GetString("OccupationMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 命途 的本地化字符串。
        /// </summary>
        public static string OccupationName {
            get {
                return ResourceManager.GetString("OccupationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 虚无 的本地化字符串。
        /// </summary>
        public static string OccupationNihility {
            get {
                return ResourceManager.GetString("OccupationNihility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 存护 的本地化字符串。
        /// </summary>
        public static string OccupationPreservation {
            get {
                return ResourceManager.GetString("OccupationPreservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 巡猎 的本地化字符串。
        /// </summary>
        public static string OccupationTheHunt {
            get {
                return ResourceManager.GetString("OccupationTheHunt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 级 的本地化字符串。
        /// </summary>
        public static string UnitLevel {
            get {
                return ResourceManager.GetString("UnitLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 % 的本地化字符串。
        /// </summary>
        public static string UnitPercent {
            get {
                return ResourceManager.GetString("UnitPercent", resourceCulture);
            }
        }
    }
}
