//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarRailDamage.Source.UI.Assets.Lang {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FixedText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FixedText() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StarRailDamage.Source.UI.Assets.Lang.FixedText", typeof(FixedText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 攻击力 的本地化字符串。
        /// </summary>
        public static string Attack {
            get {
                return ResourceManager.GetString("Attack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 基础攻击 的本地化字符串。
        /// </summary>
        public static string AttackBase {
            get {
                return ResourceManager.GetString("AttackBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 基础攻击 的本地化字符串。
        /// </summary>
        public static string AttackBaseSimple {
            get {
                return ResourceManager.GetString("AttackBaseSimple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 攻击力 的本地化字符串。
        /// </summary>
        public static string AttackSimple {
            get {
                return ResourceManager.GetString("AttackSimple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 击破伤害 的本地化字符串。
        /// </summary>
        public static string BreakDamage {
            get {
                return ResourceManager.GetString("BreakDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 击破增伤 的本地化字符串。
        /// </summary>
        public static string BreakDamageBoost {
            get {
                return ResourceManager.GetString("BreakDamageBoost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 击破增伤 的本地化字符串。
        /// </summary>
        public static string BreakDamageBoostSimple {
            get {
                return ResourceManager.GetString("BreakDamageBoostSimple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 击破 的本地化字符串。
        /// </summary>
        public static string BreakDamageSimple {
            get {
                return ResourceManager.GetString("BreakDamageSimple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 击破特攻 的本地化字符串。
        /// </summary>
        public static string BreakEffect {
            get {
                return ResourceManager.GetString("BreakEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 击破特攻 的本地化字符串。
        /// </summary>
        public static string BreakEffectSimple {
            get {
                return ResourceManager.GetString("BreakEffectSimple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 击破效率 的本地化字符串。
        /// </summary>
        public static string BreakEfficiency {
            get {
                return ResourceManager.GetString("BreakEfficiency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 击破效率 的本地化字符串。
        /// </summary>
        public static string BreakEfficiencySimple {
            get {
                return ResourceManager.GetString("BreakEfficiencySimple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 切换 的本地化字符串。
        /// </summary>
        public static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色属性 的本地化字符串。
        /// </summary>
        public static string CharacterElement {
            get {
                return ResourceManager.GetString("CharacterElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色等级 的本地化字符串。
        /// </summary>
        public static string CharacterLevel {
            get {
                return ResourceManager.GetString("CharacterLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色等级 的本地化字符串。
        /// </summary>
        public static string CharacterLevelSimple {
            get {
                return ResourceManager.GetString("CharacterLevelSimple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色命途 的本地化字符串。
        /// </summary>
        public static string CharacterOccupation {
            get {
                return ResourceManager.GetString("CharacterOccupation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 暴击伤害 的本地化字符串。
        /// </summary>
        public static string CriticalDamage {
            get {
                return ResourceManager.GetString("CriticalDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 暴击伤害 的本地化字符串。
        /// </summary>
        public static string CriticalDamageSimple {
            get {
                return ResourceManager.GetString("CriticalDamageSimple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全暴击伤害 的本地化字符串。
        /// </summary>
        public static string CriticalHitDamage {
            get {
                return ResourceManager.GetString("CriticalHitDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 暴击 的本地化字符串。
        /// </summary>
        public static string CriticalHitDamageSimple {
            get {
                return ResourceManager.GetString("CriticalHitDamageSimple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 暴击率 的本地化字符串。
        /// </summary>
        public static string CriticalHitRate {
            get {
                return ResourceManager.GetString("CriticalHitRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 暴击率 的本地化字符串。
        /// </summary>
        public static string CriticalHitRateSimple {
            get {
                return ResourceManager.GetString("CriticalHitRateSimple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 伤害提高 的本地化字符串。
        /// </summary>
        public static string DamageBoost {
            get {
                return ResourceManager.GetString("DamageBoost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 伤害提高 的本地化字符串。
        /// </summary>
        public static string DamageBoostSimple {
            get {
                return ResourceManager.GetString("DamageBoostSimple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 免伤 的本地化字符串。
        /// </summary>
        public static string DamageDecrease {
            get {
                return ResourceManager.GetString("DamageDecrease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 免伤 的本地化字符串。
        /// </summary>
        public static string DamageDecreaseSimple {
            get {
                return ResourceManager.GetString("DamageDecreaseSimple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 易伤 的本地化字符串。
        /// </summary>
        public static string DamageIncrease {
            get {
                return ResourceManager.GetString("DamageIncrease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 易伤 的本地化字符串。
        /// </summary>
        public static string DamageIncreaseSimple {
            get {
                return ResourceManager.GetString("DamageIncreaseSimple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 防御力 的本地化字符串。
        /// </summary>
        public static string Defense {
            get {
                return ResourceManager.GetString("Defense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 基础防御 的本地化字符串。
        /// </summary>
        public static string DefenseBase {
            get {
                return ResourceManager.GetString("DefenseBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 基础防御 的本地化字符串。
        /// </summary>
        public static string DefenseBaseSimple {
            get {
                return ResourceManager.GetString("DefenseBaseSimple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无视防御 的本地化字符串。
        /// </summary>
        public static string DefenseDecrease {
            get {
                return ResourceManager.GetString("DefenseDecrease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无视防御 的本地化字符串。
        /// </summary>
        public static string DefenseDecreaseSimple {
            get {
                return ResourceManager.GetString("DefenseDecreaseSimple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 防御力 的本地化字符串。
        /// </summary>
        public static string DefenseSimple {
            get {
                return ResourceManager.GetString("DefenseSimple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 持续伤害 的本地化字符串。
        /// </summary>
        public static string DelayedDamage {
            get {
                return ResourceManager.GetString("DelayedDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 效果命中 的本地化字符串。
        /// </summary>
        public static string EffectHitRate {
            get {
                return ResourceManager.GetString("EffectHitRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 效果命中 的本地化字符串。
        /// </summary>
        public static string EffectHitRateSimple {
            get {
                return ResourceManager.GetString("EffectHitRateSimple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 效果抵抗 的本地化字符串。
        /// </summary>
        public static string EffectResistance {
            get {
                return ResourceManager.GetString("EffectResistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 效果抵抗 的本地化字符串。
        /// </summary>
        public static string EffectResistanceSimple {
            get {
                return ResourceManager.GetString("EffectResistanceSimple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 抗性 的本地化字符串。
        /// </summary>
        public static string ElementResistance {
            get {
                return ResourceManager.GetString("ElementResistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 抗性 的本地化字符串。
        /// </summary>
        public static string ElementResistanceSimple {
            get {
                return ResourceManager.GetString("ElementResistanceSimple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 怪物数量 的本地化字符串。
        /// </summary>
        public static string EnemyAmount {
            get {
                return ResourceManager.GetString("EnemyAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 怪物 的本地化字符串。
        /// </summary>
        public static string EnemyAmountSimple {
            get {
                return ResourceManager.GetString("EnemyAmountSimple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 怪物等级 的本地化字符串。
        /// </summary>
        public static string EnemyLevel {
            get {
                return ResourceManager.GetString("EnemyLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 怪物等级 的本地化字符串。
        /// </summary>
        public static string EnemyLevelSimple {
            get {
                return ResourceManager.GetString("EnemyLevelSimple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 充能效率 的本地化字符串。
        /// </summary>
        public static string EnergyRegenerationRate {
            get {
                return ResourceManager.GetString("EnergyRegenerationRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 充能效率 的本地化字符串。
        /// </summary>
        public static string EnergyRegenerationRateSimple {
            get {
                return ResourceManager.GetString("EnergyRegenerationRateSimple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 期望伤害 的本地化字符串。
        /// </summary>
        public static string ExpectedDamage {
            get {
                return ResourceManager.GetString("ExpectedDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 期望值 的本地化字符串。
        /// </summary>
        public static string ExpectedDamageSimple {
            get {
                return ResourceManager.GetString("ExpectedDamageSimple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出 的本地化字符串。
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 灼烧 的本地化字符串。
        /// </summary>
        public static string FireDelayedDamage {
            get {
                return ResourceManager.GetString("FireDelayedDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 火 的本地化字符串。
        /// </summary>
        public static string FireElement {
            get {
                return ResourceManager.GetString("FireElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 特殊数值 的本地化字符串。
        /// </summary>
        public static string HealingAmount {
            get {
                return ResourceManager.GetString("HealingAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 特殊数值 的本地化字符串。
        /// </summary>
        public static string HealingAmountSimple {
            get {
                return ResourceManager.GetString("HealingAmountSimple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生命值 的本地化字符串。
        /// </summary>
        public static string Health {
            get {
                return ResourceManager.GetString("Health", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 基础生命 的本地化字符串。
        /// </summary>
        public static string HealthBase {
            get {
                return ResourceManager.GetString("HealthBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 基础生命 的本地化字符串。
        /// </summary>
        public static string HealthBaseSimple {
            get {
                return ResourceManager.GetString("HealthBaseSimple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生命值 的本地化字符串。
        /// </summary>
        public static string HealthSimple {
            get {
                return ResourceManager.GetString("HealthSimple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 冻结 的本地化字符串。
        /// </summary>
        public static string IceDelayedDamage {
            get {
                return ResourceManager.GetString("IceDelayedDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 冰 的本地化字符串。
        /// </summary>
        public static string IceElement {
            get {
                return ResourceManager.GetString("IceElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 禁锢 的本地化字符串。
        /// </summary>
        public static string ImaginaryDelayedDamage {
            get {
                return ResourceManager.GetString("ImaginaryDelayedDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 虚数 的本地化字符串。
        /// </summary>
        public static string ImaginaryElement {
            get {
                return ResourceManager.GetString("ImaginaryElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 简体中文 的本地化字符串。
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 级 的本地化字符串。
        /// </summary>
        public static string LevelUnit {
            get {
                return ResourceManager.GetString("LevelUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 触电 的本地化字符串。
        /// </summary>
        public static string LightningDelayedDamage {
            get {
                return ResourceManager.GetString("LightningDelayedDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 雷 的本地化字符串。
        /// </summary>
        public static string LightningElement {
            get {
                return ResourceManager.GetString("LightningElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 能量上限 的本地化字符串。
        /// </summary>
        public static string MaxEnergy {
            get {
                return ResourceManager.GetString("MaxEnergy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 能量上限 的本地化字符串。
        /// </summary>
        public static string MaxEnergySimple {
            get {
                return ResourceManager.GetString("MaxEnergySimple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 基础伤害 的本地化字符串。
        /// </summary>
        public static string NormalDamage {
            get {
                return ResourceManager.GetString("NormalDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 基础值 的本地化字符串。
        /// </summary>
        public static string NormalDamageSimple {
            get {
                return ResourceManager.GetString("NormalDamageSimple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 算式 的本地化字符串。
        /// </summary>
        public static string NumberTextBoxTitle {
            get {
                return ResourceManager.GetString("NumberTextBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 治疗提高 的本地化字符串。
        /// </summary>
        public static string OutgoingHealingBoost {
            get {
                return ResourceManager.GetString("OutgoingHealingBoost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 治疗提高 的本地化字符串。
        /// </summary>
        public static string OutgoingHealingBoostSimple {
            get {
                return ResourceManager.GetString("OutgoingHealingBoostSimple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 % 的本地化字符串。
        /// </summary>
        public static string PercentUnit {
            get {
                return ResourceManager.GetString("PercentUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 裂伤 的本地化字符串。
        /// </summary>
        public static string PhysicalDelayedDamage {
            get {
                return ResourceManager.GetString("PhysicalDelayedDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物理 的本地化字符串。
        /// </summary>
        public static string PhysicalElement {
            get {
                return ResourceManager.GetString("PhysicalElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 纠缠 的本地化字符串。
        /// </summary>
        public static string QuantumDelayedDamage {
            get {
                return ResourceManager.GetString("QuantumDelayedDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 量子 的本地化字符串。
        /// </summary>
        public static string QuantumElement {
            get {
                return ResourceManager.GetString("QuantumElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 抗性穿透 的本地化字符串。
        /// </summary>
        public static string ResistanceDecrease {
            get {
                return ResourceManager.GetString("ResistanceDecrease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 抗性穿透 的本地化字符串。
        /// </summary>
        public static string ResistanceDecreaseSimple {
            get {
                return ResourceManager.GetString("ResistanceDecreaseSimple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 的本地化字符串。
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置 的本地化字符串。
        /// </summary>
        public static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 速度 的本地化字符串。
        /// </summary>
        public static string Speed {
            get {
                return ResourceManager.GetString("Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 基础速度 的本地化字符串。
        /// </summary>
        public static string SpeedBase {
            get {
                return ResourceManager.GetString("SpeedBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 基础速度 的本地化字符串。
        /// </summary>
        public static string SpeedBaseSimple {
            get {
                return ResourceManager.GetString("SpeedBaseSimple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 速度 的本地化字符串。
        /// </summary>
        public static string SpeedSimple {
            get {
                return ResourceManager.GetString("SpeedSimple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 超击破伤害 的本地化字符串。
        /// </summary>
        public static string SuperBreakDamage {
            get {
                return ResourceManager.GetString("SuperBreakDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 超击破 的本地化字符串。
        /// </summary>
        public static string SuperBreakDamageSimple {
            get {
                return ResourceManager.GetString("SuperBreakDamageSimple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 超击破 的本地化字符串。
        /// </summary>
        public static string SuperBreakEqual {
            get {
                return ResourceManager.GetString("SuperBreakEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 超击破 的本地化字符串。
        /// </summary>
        public static string SuperBreakEqualSimple {
            get {
                return ResourceManager.GetString("SuperBreakEqualSimple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 韧性值 的本地化字符串。
        /// </summary>
        public static string Toughness {
            get {
                return ResourceManager.GetString("Toughness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 削韧值 的本地化字符串。
        /// </summary>
        public static string ToughnessReduced {
            get {
                return ResourceManager.GetString("ToughnessReduced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 削韧值 的本地化字符串。
        /// </summary>
        public static string ToughnessReducedSimple {
            get {
                return ResourceManager.GetString("ToughnessReducedSimple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 韧性值 的本地化字符串。
        /// </summary>
        public static string ToughnessSimple {
            get {
                return ResourceManager.GetString("ToughnessSimple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 风化 的本地化字符串。
        /// </summary>
        public static string WindDelayedDamage {
            get {
                return ResourceManager.GetString("WindDelayedDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 风 的本地化字符串。
        /// </summary>
        public static string WindElement {
            get {
                return ResourceManager.GetString("WindElement", resourceCulture);
            }
        }
    }
}
